apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadence-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cadence-operator
  template:
    metadata:
      labels:
        name: cadence-operator
    spec:
      serviceAccountName: cadence-operator
      containers:
        - name: cadence-operator
          # Replace this with the built image name
          image: gcr.io/codelity-co/cadence-operator:v0.1.0
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cadence-operator"
